[package]
name = "score-czech"
version = "0.1.0"
authors = ["William Kunkel <will@wkunkel.com>"]

[dependencies]
iron = "*"
router = "*"
rand = "*"
lazy_static = "*"
hyper = "*"
serde_json = "*"
itertools = "*"